# This workflow will do a clean install of node dependencies and run tests

name: Continuous Integration

on: push

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18.20.8'
      - run: yarn install --immutable
      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test
      - run: yarn prepack

  check-licenses:
    name: Check licenses
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18.20.8'
      - run: yarn install --immutable
      - run: yarn check-licenses
